approveManualInstallPlanViaHook: true

installPlanApproverAndVerifyJobsImage: quay.io/openshift/origin-cli:4.15

installPlanApproverAndVerifyJobsTolerations:
- key: "infra"
  operator: "Equal"
  value: "true"
  effect: "NoSchedule"

operatorGroups:
- name: argocd-operator-9
  createNamespace: true
  targetOwnNamespace: false
  otherTargetNamespaces:

operators:
- name: argocd-operator
  channel: alpha
  csv: argocd-operator.v0.16.0
  installPlanApproval: Manual
  source: operatorhubio-catalog
  sourceNamespace: olm
  namespace: argocd-operator-9
  installPlanVerifierActiveDeadlineSeconds: 1200
