name: Validate

on:
  workflow_dispatch:
  push:
    paths:
      - '!README.md'
      - '!.github/**'
      - '.github/workflows/conftest.yaml'
  pull_request:
    paths:
      - '!README.md'
      - '!.github/**'
      - '.github/workflows/conftest.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  conftest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Conftest
        uses: redhat-cop/github-actions/confbatstest@cc45c69b6655161f278271cd0c68ddcc1444a3f8 # v4.6
        with:
          tests: _test/conftest.sh
