name: Validate

on:
  push:
    paths-ignore:
      - '.github/**'
      - 'README.md'
  pull_request:
    paths-ignore:
      - '.github/**'
      - 'README.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  conftest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Conftest
        uses: redhat-cop/github-actions/confbatstest@561af5e610560aef3210ca7a08fe73b2add97648 # v4.5
        with:
          tests: _test/conftest.sh
